export const DEFAULT_CALIBRATED_SCALE_M_PER_PX = 0.333;
export const DEFAULT_CALIBRATED_SCALE_MM_PER_PX = DEFAULT_CALIBRATED_SCALE_M_PER_PX * 1000;
export const DEFAULT_CALIBRATED_SCALE_LABEL = "Scale: 0.333 m/px (calibrated)";
